package com.roland.android.calculator.util

object Constants {
    const val THEME = "theme"
    const val DEG_RAD = "rad_deg"

    const val ADD = "+"
    const val MINUS = "−"
    const val DIVIDE = "÷"
    const val MULTIPLY = "×"
    const val MOD = "%"
    const val SIN = "sin("
    const val COS = "cos("
    const val TAN = "tan("
    const val SINR = "sinr("
    const val COSR = "cosr("
    const val TANR = "tanr("
    const val SIN_INV = "sin⁻¹("
    const val COS_INV = "cos⁻¹("
    const val TAN_INV = "tan⁻¹("
    const val ASIN = "asin("
    const val ACOS = "acos("
    const val ATAN = "atan("
    const val ASINR = "asinr("
    const val ACOSR = "acosr("
    const val ATANR = "atanr("
    const val LOG = "log("
    const val INV_LOG = "10^"
    const val PI = "π"
    const val DOT = "."
    const val ROOT = "√("
    const val SQUARE = "^"
    const val SQUARED = "²"
    const val DEG = "DEG"
    const val RAD = "RAD"
    const val EULER = "e"
}